<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container7j19jeq\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container7j19jeq/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container7j19jeq.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container7j19jeq\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container7j19jeq\App_KernelDevDebugContainer([
    'container.build_hash' => '7j19jeq',
    'container.build_id' => '1a8c74bc',
    'container.build_time' => 1639492617,
], __DIR__.\DIRECTORY_SEPARATOR.'Container7j19jeq');
